// Generated by CoffeeScript 1.6.2
var assert, code_eq, compile, minify, p, run, strip;

assert = require('assert');

compile = require('../lib/coffee-script').compile;

minify = require('uglify-js').minify;

p = console.log;

strip = function(code) {
  var res;

  res = minify(code, {
    fromString: true,
    output: {
      beautify: true
    }
  });
  return res.code;
};

code_eq = function(src_orig, dest_orig) {
  var dest, e, src, src_gened;

  try {
    src = strip(src_gened = compile(src_orig));
    dest = "(function(){" + dest_orig + "}).call(this)";
    dest = strip(dest);
    return assert.equal(src, dest);
  } catch (_error) {
    e = _error;
    console.log("<<<<");
    console.log(src_orig);
    console.log('----');
    console.log(src_gened);
    console.log("----");
    console.log(dest_orig);
    console.log(">>>>");
    throw e;
  }
};

run = function(code, cb) {
  console.log('a');
  return console.log(compile("(autocb) -> " + code, {
    bare: true
  }));
};

module.exports = {
  code_eq: code_eq,
  p: p,
  compile: compile,
  run: run
};
