// Generated by CoffeeScript 1.6.3
var code_eq, p, _ref;

_ref = require('./helper'), p = _ref.p, code_eq = _ref.code_eq;

describe('logical', function() {
  it('||', function() {
    return code_eq("a! || b!", "			  var _this = this;\n\n			  (function(_$cb$_2) {\na(function(_$$_0) {\n  if (_$$_0) {\n	_$cb$_2(_$$_0);\n  } else {\n	b(function(_$$_1) {\n	  _$cb$_2(_$$_1);\n	});\n  }\n});\n			  })(function(_$$_3) {\nreturn _$$_3;\n			  });");
  });
  it('&&', function() {
    return code_eq("a! && b!", "			  var _this = this;\n\n			  (function(_$cb$_2) {\na(function(_$$_0) {\n  if (!_$$_0) {\n	_$cb$_2(_$$_0);\n  } else {\n	b(function(_$$_1) {\n	  _$cb$_2(_$$_1);\n	});\n  }\n});\n			  })(function(_$$_3) {\nreturn _$$_3;\n			  });");
  });
  it('?', function() {
    return code_eq("a! ? b!", "			  var _this = this;\n\n			  (function(_$cb$_2) {\na(function(_$$_0) {\n  if (_$$_0 != null) {\n	_$cb$_2(_$$_0);\n  } else {\n	b(function(_$$_1) {\n	  _$cb$_2(_$$_1);\n	});\n  }\n});\n			  })(function(_$$_3) {\nreturn _$$_3;\n			  });");
  });
  it('&&=', function() {
    return code_eq("a &&= b!", "			  var a,\n_this = this;\n\n			  (function(_$cb$_0) {\nif (!a) {\n  _$cb$_0(a);\n} else {\n  b(function() {\n	_$cb$_0(a = arguments[0]);\n  });\n}\n			  })(function(_$$_1) {\nreturn _$$_1;\n			  });");
  });
  it('||=', function() {
    return code_eq("a ||= b!", "			  var a,\n_this = this;\n\n			  (function(_$cb$_0) {\nif (a) {\n  _$cb$_0(a);\n} else {\n  b(function() {\n	_$cb$_0(a = arguments[0]);\n  });\n}\n			  })(function(_$$_1) {\nreturn _$$_1;\n			  });");
  });
  it('?=', function() {
    return code_eq("a ?= b!", "			  var a,\n_this = this;\n\n			  (function(_$cb$_0) {\nif (typeof a !== \"undefined\" && a !== null) {\n  _$cb$_0(a);\n} else {\n  b(function() {\n	_$cb$_0(a = arguments[0]);\n  });\n}\n			  })(function(_$$_1) {\nreturn _$$_1;\n			  });");
  });
  return it('complex', function() {
    return code_eq("x = a && b! || c! && d!", "var x,\n  _this = this;\n\n(function(_$cb$_8) {\n  (function(_$cb$_5) {\n	(function(_$cb$_2) {\n	  if (!a) {\n		_$cb$_2(a);\n	  } else {\n		b(function(_$$_1) {\n		  _$cb$_2(_$$_1);\n		});\n	  }\n	})(function(_$$_3) {\n	  if (_$$_3) {\n		_$cb$_5(_$$_3);\n	  } else {\n		c(function(_$$_4) {\n		  _$cb$_5(_$$_4);\n		});\n	  }\n	});\n  })(function(_$$_6) {\n	if (!_$$_6) {\n	  _$cb$_8(_$$_6);\n	} else {\n	  d(function(_$$_7) {\n		_$cb$_8(_$$_7);\n	  });\n	}\n  });\n})(function(_$$_9) {\n  _$cb$_0(_$$_9);\n});\nfunction _$cb$_0() {\n  return x = arguments[0];\n};");
  });
});
