// Generated by CoffeeScript 1.6.2
var code_eq, p, _ref;

_ref = require('./helper'), p = _ref.p, code_eq = _ref.code_eq;

describe('mathmatics', function() {
  it('simple', function() {
    return code_eq("a! + b!", "a(function(_$$_0) {\n	b(function(_$$_1) {\n		return _$$_0 + _$$_1;\n	});\n});");
  });
  it('assign', function() {
    return code_eq("x = a! + b!", "var x,\n  _this = this;\n\na(function(_$$_1) {\n  b(function(_$$_2) {\n	_$cb$_0(_$$_1 + _$$_2);\n  });\n});\nfunction _$cb$_0() {\n  return x = arguments[0];\n};\n");
  });
  return it('mix async and sync', function() {
    return code_eq("x = a + b + c! + d + e", "var x,\n  _this = this;\n\na + b;\nfunction _$cb$_3(_$$_4) {\n  c(function(_$$_5) {\n	_$cb$_2(_$$_4 + _$$_5);\n  });\n};\nfunction _$cb$_2(_$$_6) {\n  _$cb$_1(_$$_6 + d);\n};\nfunction _$cb$_1(_$$_7) {\n  _$cb$_0(_$$_7 + e);\n};\nfunction _$cb$_0() {\n  return x = arguments[0];\n};\n");
  });
});
